Worlds:
  ManagedWorld: world
  CityWorld: flat
Spawning:
  NewPlayersSpawnInHomeRegion: true
  RespawnInHomeRegion: true
Teleporting:
  AllowTeleportation: true
  TeleportFromAnywhere: false
  PostTeleportRadius: 25
  TeleportViaOtherSigns: false
Scanning:
  ScanOnRestart: true
  HoursBetweenResourceScans: 6
  DensityRatio: 1.0
  LimitEntities: true
  HoursBetweenEntityScans: 1
ChunkLimits:
  MaximumAnimalsPerChunk: 20
  MaximumMonstersPerChunk: 8
  MaximumVillagersPerChunk: 5
  MaximumGolemsPerChunk: 5
  MaximumDropsPerChunk: 25
Queueing:
  MaxIdleMinutes: 10
  LoginQueueEnabled: true
  MinimumPlayersOnlineForIdleBoot: 5
  ReservedSlotsForAdministrators: 1
  LoginQueueMessage: '%queuePosition% of %queueLength% in queue. Your queue position will reset in 3 minutes'
Misc:
  GrassRegrows: true
  AnimalsRespawn: true
  TreesRegrow: true
  PrintResourceScanResults: true
  PrintEntityScanResults: false
  EnableDebugLogging: false
Regions:
  BuildNamedPosts: true
  BuildWildrenessPosts: true
  MinimumRegionPostY: 62
  PostProtectionRadius: 10
  CustomSigns:
    Main:
    - ''
    - Population
    - Density
    - ''
    North:
    - ''
    - ''
    - ''
    - ''
    South:
    - ''
    - ''
    - ''
    - ''
    East:
    - ''
    - ''
    - ''
    - ''
    West:
    - ''
    - ''
    - ''
    - ''